config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'privacy', to: 'pages#privacy'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
	end
	
	def privacy
	end

	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb

  </hr>
        <footer class="text-center">
          <div class="container">
          <p>
            &copy; Seater 2018. All Rights Reserved.
          </p>
          <ul class="list-inline">
        
            <li class="list-inline-item">
              <li><%= link_to 'Privacy Policy', privacy_path, class: "list-inline-item" %></li>
            </li>
          </ul>
      </div>
    </footer>


app/views/layouts/_navigation.html.erb

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
    	<div class="navbar-toggler-right" >
	   <ul class="nav navbar-nav navbar-right">
		    <li><%= link_to "How to", class: "navbar-brand" %></li>
		    <li><%= link_to "Download", anchor:'download', class: "navbar-brand" %></li>
		    <li><%= link_to "About", anchor:'about', class: "navbar-brand" %></li>
		    <li><%= link_to "Contact Us", anchor:'contact', class: "navbar-brand"%></li>
		    
	  	</ul>
	  </div>

	</div>
</div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Seater" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= render 'layouts/navigation' %>

    <div class="center">
      <div class="row">
        <div class="col-lg-16">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>
   <!-- /container -->

      <footer>
        <%= render 'layouts/footer' %>
      </footer>

<!-- /container -->

  </body>
</html>

app/views/pages/index.html.erb
	
	<div class="jumbotron img-responsive container-fluid col-md-14">
		<div class="stitched">
			<%= image_tag "logo.png", :class => "seater" %>
			<h4> Transportation has never been easier. </h4>
		</div>
	</div>
	
	<div class="container">

			
			<%= image_tag "appicon.png", :class => "appicon" %>
			
			<%= image_tag "phone.png", :class => "phone" %>

			<div class="style-text">
				<h3>
					<b> We are changing everything you</br>
					know about transportation! </b></br>
					<a>
						Through our app you can do</br> 
						anything from booking your</br> 
						daily commute, to intercity travel,</br> 
						and everything in between! </a>
				</h3></br>
				<a><strong>What are you waiting for?</strong></a>				
			</div>
	</div>

	<div class="container" id="download">
		<%= link_to image_tag("googlestore.png", class: "img-responsive center-block ps"), root_path %>
		<%= link_to image_tag("like.png", class: "img-responsive center-block fb"), "https://www.facebook.com/SeaterApp/" %></br></br></br>
	<table id="about">
	  <tr>
	    <th>About </th>
	    
	  </tr>
	  <tr>
	    <td>We are a group of five, that have invested a lot of time, and effort to create a unique mass transport solution.</br>
		Please download our app, and try it out. Never hesitate to report any problems you may encounter through the contact us section in the app settings, or through the contact us section here on the website.</br>
		Have a nice ride!</br></td>
	</tr>
</table></br></br></br>

<table id="contact">
	<tr>
		<th>Contact Us</th>
	</tr>
	<tr>
	    <td>You can always reach us through our email; <span style="color:#0071F3;">seaterapp@gmail.com</span>, through the contact us section in the app settings.</br>
		We are always have to receive feedback, and to help you with any problems you may encounter.</td>
	  </tr>

	</table></br></br></br>
	
		
</div>



app/views/pages/privacy.html.erb

<div class="style-background">
<div class="container">
	</br><p><strong> USER PRIVACY STATEMENT: </strong></br>
	Effective after: October 15th 2017</p></br>


	<p>Under the legal name of Rakkebny LLC, Seater collects information about you when you use our mobile applications, websites, and other online products and services. In addition to other interactions and communications you have with us.If you choose to use our Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that we collect is used for providing and improving the service. We will not use or share your information with anyone except as described in this Privacy Policy.</p></br>

	<p><strong>General Scope</strong></p></br>

	<p>This Privacy Statement (“Statement") applies to people, regardless where they are located in the world who use our apps or services to request transportation, delivery, or other services. 
	This Statement does not apply to information we collect from or about drivers, couriers, partner transportation companies, or any other persons who use the Seater platform under license.</p></br>

	<p><strong>Collection of Information</strong></p></br>

	<p><strong>Information Provided By Users</strong></br>
	We collect information that users provide directly to us, such as when you create or modify your account, request services and provide relevant information, contact our customer support, or willingly communicate them with us. This information may include: name, email, phone number, postal address, profile picture, payment method, and other information you choose to provide.</p></br>





	<p><strong>Information collected through using our services.</strong></br>
	By using our services, you agree to the following usages.</p></br>

	<p>Location Information: When you use our transportation services, we collect precise location data to ensure proper communication between our users, and our partner drivers.  We may also collect the precise location of your device when the app is running in the foreground or background. We may also derive your approximate location from your IP address.</p></br>

	<p>User interactions information:  We collect details related to users’ use of our services, including the type of service requested, date, or time the service was provided, amount charged, distance traveled, and other related details. We use this information to improve our services, and to better cater to our users needs in the future.</p></br>

	<p>Usage and Preference Information:  We collect information about how you and site visitors interact with our Services, preferences expressed, and settings chosen. In some cases we do this through the use of cookies, pixel tags, and similar technologies that create and maintain unique identifiers.</p></br>

	<p>Device Information: We may collect information about your mobile device, including, for example, the hardware model, operating system and version, software, preferred language, advertising identifiers, serial number, device motion information, and mobile network information.</p></br>

	<p>Log Information: Upon using our services, we collect server logs, which may have information such as, access dates and times, app crashes and other system activity, device IP address, type of browser, app features or pages viewed.</p></br>

	<p><strong>Children Under Thirteen</strong></br>
	Regarding children below the age of thirteen, Seater does not intentionally, and knowingly collect personally identifiable information from children below the age of thirteen. If you are under the age of thirteen, you require your parents, or guardians permission before using our application.</p></br>

	<p><strong>Other sources of information</strong></br>
	We may also receive information from other sources and this information will join the information we collect through our services.</p> </br>

	<p>For example:</br></br>
	<ul class="a">
	  <li>If you choose to link, create, or log in to your Seater account using a social media service (Ex:Facebook), or if you engage with a separate app or website that uses our API (or whose API we use), we may receive information about you or your connections from that site or app.</br></li>
	</ul></p>

	<p><strong>Use of Information</strong></br>
	We may use the information we collect about you to:</p></br>

	<ul class="a">
	  <li>Provide, maintain, and improve our services, and that includes the following actions as an example to, let you successfully use our product, process payments, send receipts, develop and improve our product to better fit our users needs, provide customer support to users and drivers, develop safety features, authenticate users, and send product updates and administrative messages</li></br>

	  <li>To ensure control over misuse of our application, for example, to prevent fraud and abuse cases of our services. Also to fix bugs and operational problems, to learn from our data analysis, testing, and research, and to monitor and analyze trends.</li></br>

	  <li>To successfully communicate changes between users and our partner drivers.</li></br>

	  <li>Send you communications we think will be of interest to you, including information about products, services, promotions, news, and events of Seater and other companies, where permissible and according to local applicable laws; and to process contest, sweepstake, or other promotion entries and fulfill any related awards;</li></br>

	  <li>Personalize and improve the Services, including to provide or recommend features, content, social connections, referrals, and advertisements.</li>
	</ul>

	<p>The Sharing Of Information</br>
	We share the information provided by users in the following contexts;</p></br>

	<p><strong>Through Our Services</strong></br>
		<ul>
			<li>With drivers to enable them to provide the services we provide. For example, we share your name, photo (if you provide one), and accurate pickup locations with Drivers.</li></br>

			<li>Third Party sharing due to promotional deals, or other partnerships.</li></br>

			<li>With third parties with whom you choose to let us share information, for example other apps or websites that integrate with our API or Services, or those with an API or Service with which we integrate; and</li></br>
		</ul>

	</p>
	<p><strong>Other Important Sharing</strong></br>
		We may share your information:
	<ul>
		<li>With vendors, consultants, marketing partners, and other service providers who need access to such information to carry out work on our behalf.</li></br>

		<li>We will share your information with law enforcement authorities, or government authorities if misuse of our services is spotted or is requested from us within the law.</li></br>

		<li>In connection with, or during negotiations of, any merger, sale of company assets, consolidation or restructuring, financing, or acquisition of all or a portion of our business by or into another company;</li></br>
	</ul>

	</p>

	<p><strong>Social Media Integration</strong></br>
	If integrated with any social media platform, and the data provided to us is shared with another social media network, please read the privacy policy of said network.</p></br>

	<p><strong>Your Rights</p></br>

	<p>Account Information</strong></br>
	You may correct your account information at any time by logging into your online or in-app account.</br>
	If you wish to cancel your account, please email us at seaterapp@gmail.com.</p> </br>

	<p>Please know that in some cases we will choose to temporarily retain certain information about you as required by law, or for crucial business purposes to the extent permitted by law. For instance, if you have standing debt or if we believe you have committed fraud or violated our terms, we may seek resolve before deleting your information.</p></br>

	<p><strong>Access Rights</strong></br>
	Seater will comply with individual’s requests regarding access, correction, and/or deletion of the personal data it stores in accordance with applicable law.</p></br>

	<p><strong>Changes to the Statement</strong></br>
	This document may change from time to time, and we will do our job to notify you whenever a major change occurs.</p> </br>



	<p><strong>Contact Us</strong></br>
	If you have any questions about this Privacy Statement, please contact us at seaterapp@gmail.com.</p></br>


</div>
</div>